checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*

build:
    tests:
        before:
            -
                command: 'composer require --no-interaction --no-suggest "orchestra/testbench:^3.6"'
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
    nodes:
        php:
            environment:
                php: 7.3
