dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  matrix:
    - LARAVEL=^6.0
    - LARAVEL=^7.0

matrix:
  fast_finish: true

before_install:
  # Must be before any additional files are created
  - test "$(find . -type f -not -path "./.git/*" -perm /111)" == ./tests/laravel-test.sh

install:
  - composer validate --strict
  - travis_retry composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script:
  - composer test
  - export -f travis_retry
  - tests/laravel-test.sh
  # Check for copyright messages
  - test -z "$(grep -r -L '(c)\s*Nuno Maduro.*enunomaduro@gmail\.com' src/)"
