language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update --no-interaction --no-suggest ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyze
  - export -f travis_retry
  - tests/laravel-test.sh
  # Check for copyright messages
  - test -z "$(grep -r -L '(c)\s*Nuno Maduro.*enunomaduro@gmail\.com' src/)"
