language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  matrix:
    - COMPOSER_FLAGS=""

before_install:
  # Must be before any additional files are created
  # TODO TravisCI moved to GCE, see https://travis-ci.community/t/file-permissions-just-gone-up-to-664/1547?u=szepeviktor
  - test "$(find . -type f -not -path "./.git/*" -not -perm 0664)" == ./tests/laravel-test.sh

install:
  - travis_retry composer update --no-interaction --no-suggest ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyze
  - export -f travis_retry
  - tests/laravel-test.sh
  # Check for copyright messages
  - test -z "$(grep -r -L '(c)\s*Nuno Maduro.*enunomaduro@gmail\.com' src/)"
