language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - composer create-project --quiet --prefer-dist "laravel/laravel" laravel && cd laravel/
  # Add package from source
  - sed -e 's|"type": "project",|&\n"repositories": [ { "type": "vcs", "url": "../" } ],|' -i composer.json
  - composer require --dev nunomaduro/larastan
  # Fix https://github.com/laravel/framework/pull/23825
  - sed -e 's|@return \\Illuminate\\Http\\Response$|@return \\Symfony\\Component\\HttpFoundation\\Response|' -i app/Exceptions/Handler.php
  - php artisan code:analyse --level=max
